[package]
name = "can-types"
version = "0.1.4"
edition = "2021"

[dependencies]
anyhow = {version = "1.0.83", default-features = false}
bitfield-struct = {version = "0.6.1", default-features = false}
