name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v4
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --verbose
    - name: Build docs
      run: cargo doc
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: |
          if [[ ${{ matrix.toolchain }} == 'stable' ]]; then
            rustup component add clippy
            cargo clippy -- -W clippy::pedantic
          else
            echo "We run clippy on stable only."
          fi
